fixed find

diff --git a/scripts/ffind b/scripts/ffind
--- a/scripts/ffind
+++ b/scripts/ffind
@@ -1,23 +1,36 @@
+# /bin/sh
 #echo "searching the following locations: ${@:-.}"
 
 # optional argument to specify depth of search
 # user would specify this like "-d 2" for example
 
+depth=""
+dirs="."
+
 # parse arguments
+# -d is the depth argument
+# all other arguments should be directories and will be searched
+# if no directories are specified, the current directory will be searched
 while getopts ":d:" opt; do
   case $opt in
-    d) depth="$OPTARG"
-    ;;
-    \?) echo "Invalid option -$OPTARG" >&2
-    ;;
+    d)
+      depth="$OPTARG"
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      ;;
   esac
 done
 
-# if depth is specified, use it
+shift $((OPTIND -1))
+
+# Directories passed in as non-option arguments
+directories="$@"
+
 # otherwise, search all directories
 if [ -z "$depth" ]; then
-  find ${ :-.} -type f,d 2>/dev/null | fzf
+    echo "depth is empty"
+    find $directories -type f,d  | fzf
 else
-  find -maxdepth $depth -type f,d 2>/dev/null | fzf
+    find $directories -maxdepth $depth  -type f,d  | fzf
 fi
-# find ${depth:-} ${@:-.} -type f 2>/dev/null | fzf
